apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacity
  template:
    metadata:
      labels:
        app: udacity
    spec:
      containers:
      - name: udacity
        image: handuy1992/final-proj:v1
        ports:
        - containerPort: 8000
